[workspace]
members = ["kiva-cut", "frontend/src-tauri"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Justyer <1554694323@qq.com>"]
license = "MIT"
repository = "https://github.com/fxkt-tech/cluv"
